"""Error analysis of the model runs in the latest E1: where the local-model agents went wrong.

Reads only committed artefacts (results/e1_runs/LATEST and the runs it lists) and writes
docs/generated/error_analysis.md. Offline and deterministic. Usage: uv run python scripts/error_analysis.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from discoverylab import toolbox  # noqa: E402
from discoverylab.critic import expected_verdict  # noqa: E402
from discoverylab.models import RunState  # noqa: E402


def main() -> None:
    base = ROOT / "results" / "e1_runs"
    latest = (base / "LATEST").read_text().strip()
    rows = json.loads((base / latest / "runs.json").read_text())
    runs = [r for r in rows if r["status"] == "complete" and r["reasoner"] != "rule"]
    states = [RunState.model_validate_json((ROOT / "runs" / r["run_id"] / "state.json").read_text()) for r in runs]

    no_evidence = [s.run_id for s in states if not s.evidence]
    designs = [(s, d) for s in states for d in s.designs]
    problems = Counter(p.split(" '")[0].split(' "')[0] for _, d in designs for p in toolbox.validate(d))
    unrunnable = [d for _, d in designs if toolbox.validate(d)]
    mismatch: list[tuple[str, str, bool]] = []
    for s, d in designs:
        h = {x.id: x for x in s.hypotheses}.get(d.hypothesis_id)
        if h and d.metrics and d.metrics[0] != h.dependent_variable:
            mismatch.append((h.dependent_variable, d.metrics[0], d.metrics[0] in toolbox.METRICS))
    verdicts = []
    for s in states:
        hyps, ds, res = {h.id: h for h in s.hypotheses}, {d.id: d for d in s.designs}, {r.id: r for r in s.results}
        for k in s.conclusions:
            r, h = res.get(k.result_id), hyps.get(k.hypothesis_id)
            if r and h and r.design_id in ds:
                verdicts.append((k.verdict, expected_verdict(h, ds[r.design_id], r)))
    open_crit = Counter(
        (c.reviewer, c.issue if c.reviewer == "rule" else "(free text)", c.severity)
        for s in states
        for c in s.critiques
        if c.resolution == "open"
    )

    out = [
        "# Error analysis of the local-model runs",
        "",
        f"Generated by `scripts/error_analysis.py` from `results/e1_runs/{latest}`. Do not edit by hand.",
        "",
        f"- Completed model runs: {len(states)} (arms local, local+mc, local-b5).",
        f"- Runs with no evidence at all: {len(no_evidence)}.",
        f"- Designs: {len(designs)}; unrunnable (named something outside the toolbox catalogue): {len(unrunnable)}.",
        f"- Primary metric differs from the hypothesis's dependent variable by exact name: {len(mismatch)}; "
        f"of these the primary metric is a catalogue metric (the design runs): {sum(m[2] for m in mismatch)}.",
        f"- Conclusions checked against the fixed verdict rule: {len(verdicts)}; "
        f"verdict differs from the rule: {sum(a != b for a, b in verdicts)}.",
        "",
        "## Why designs were unrunnable",
        "",
        "| Problem | Designs |",
        "|---|---:|",
        *[f"| {k} | {v} |" for k, v in problems.most_common()],
        "",
        "## Verdict errors (model verdict, verdict the rule gives on the same statistics)",
        "",
        "| Model said | Rule says | Conclusions |",
        "|---|---|---:|",
        *[f"| {a} | {b} | {n} |" for (a, b), n in Counter(v for v in verdicts if v[0] != v[1]).most_common()],
        "",
        "## Primary metric versus dependent variable",
        "",
        "| Dependent variable (hypothesis) | Primary metric (design) | Catalogue metric |",
        "|---|---|---|",
        *[f"| {a} | {b} | {'yes' if c else 'no'} |" for (a, b, c), _ in Counter(mismatch).most_common()],
        "",
        "## Critiques still open on the final states",
        "",
        "| Reviewer | Issue | Severity | Critiques |",
        "|---|---|---|---:|",
        *[f"| {r} | {i} | {v} | {n} |" for (r, i, v), n in open_crit.most_common()],
        "",
    ]
    path = ROOT / "docs" / "generated" / "error_analysis.md"
    path.write_text("\n".join(out), encoding="utf-8")
    print("\n".join(out[4:9]))


if __name__ == "__main__":
    main()
